# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20171121_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Person'),
        ),
    ]
