# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20171123_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_person', to='contacts.Person'),
        ),
    ]
